#!/usr/bin/env bash
# Local AD Desk — fast edit loop before droplet.
# Hosts on http://127.0.0.1:8080 (localhost = secure context → mic works).
# Opens in Xplor when installed.
#
# Usage:
#   ./scripts/desk_dev.sh
#   ./scripts/desk_dev.sh --no-open
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

OPEN_BROWSER=1
for arg in "$@"; do
  case "$arg" in
    --no-open) OPEN_BROWSER=0 ;;
    -h|--help)
      echo "Usage: $0 [--no-open]"
      exit 0
      ;;
  esac
done

PORT="${DESK_PORT:-8080}"
HOST="${DESK_HOST:-127.0.0.1}"

# --- venv ---
if [[ ! -d .venv ]]; then
  echo "==> Creating .venv"
  python3 -m venv .venv
fi
# shellcheck disable=SC1091
source .venv/bin/activate
pip install -q -r requirements.txt

# --- local .env (never commit) ---
if [[ ! -f .env ]]; then
  TOKEN="$(python3 -c 'import secrets; print(secrets.token_urlsafe(24))')"
  cat > .env <<EOF
# Local AD Desk — generated by scripts/desk_dev.sh
# Do not commit. Copy XAI_API_KEY from droplet/.env if you need voice STT.

DESK_API_TOKEN=${TOKEN}
DESK_USER_ID=1
DESK_HOST=127.0.0.1
DESK_PORT=${PORT}
DESK_RELOAD=true
DESK_VOICE_TTS=true
DESK_ALLOW_LIVE_ORDERS=false
ALERTS_FILE=data/alerts.json
LOG_LEVEL=INFO

# Paste your key for Grok voice + tool agent:
# XAI_API_KEY=xai-...
# XAI_API_BASE=https://api.x.ai/v1
# XAI_CHAT_MODEL=grok-4.5
EOF
  echo "==> Created .env with a new DESK_API_TOKEN (add XAI_API_KEY for voice)"
else
  # Ensure reload for local unless explicitly set
  if ! grep -qE '^DESK_RELOAD=' .env 2>/dev/null; then
    echo "DESK_RELOAD=true" >> .env
  fi
fi

# shellcheck disable=SC1091
set -a
# shellcheck disable=SC1091
source .env
set +a

TOKEN="${DESK_API_TOKEN:-}"
if [[ -z "$TOKEN" ]]; then
  echo "ERROR: DESK_API_TOKEN empty in .env"
  exit 1
fi

mkdir -p data

# Free port if a stale desk is listening
if command -v lsof >/dev/null 2>&1; then
  PIDS="$(lsof -ti tcp:"${PORT}" -sTCP:LISTEN 2>/dev/null || true)"
  if [[ -n "${PIDS}" ]]; then
    echo "==> Port ${PORT} in use — stopping: ${PIDS}"
    # shellcheck disable=SC2086
    kill ${PIDS} 2>/dev/null || true
    sleep 0.5
  fi
fi

URL="http://127.0.0.1:${PORT}/?token=${TOKEN}"

echo ""
echo "=============================================="
echo "  AD Desk LOCAL (fast loop)"
echo "  ${URL}"
echo ""
echo "  Edit mexc_bot/webapi/** → auto-reload"
echo "  Static JS/CSS: hard-refresh (Cmd+Shift+R)"
echo "  Mic works on localhost (no Caddy needed)"
echo "  Droplet later: git push + ./scripts/desk_https_up.sh"
echo "=============================================="
echo ""

if [[ -z "${XAI_API_KEY:-}" && -z "${GROK_API_KEY:-}" ]]; then
  echo "NOTE: XAI_API_KEY not set — UI + CRUD work; voice STT needs the key in .env"
  echo ""
fi

open_xplor() {
  # Give uvicorn a moment
  sleep 1.2
  if [[ -d /Applications/Xplor.app ]]; then
    open -a Xplor "$URL" && echo "==> Opened in Xplor"
  elif command -v open >/dev/null 2>&1; then
    open "$URL" && echo "==> Opened in default browser (install Xplor for preferred browser)"
  fi
}

if [[ "$OPEN_BROWSER" == "1" ]]; then
  open_xplor &
fi

export DESK_RELOAD=true
export DESK_HOST="${HOST}"
export DESK_PORT="${PORT}"
exec python -m mexc_bot.webapi
